### ISSUE TITLE
Incompatible data types error

### ISSUE THREAD

**Issue by Sakits** [bhansconnect/alphazero-pybind11#1] opened 2022-04-08 04:29 UTC
When I run `game_runner.py`, I got the following error.
```
Build Amazing Network:   0%|            | 1/200 [08:25<27:56:48, 505.57s/it, best=1, elo=194, win_rates=['0.504', '0.496', '0.000'], vloss=0.977, ploss=5.81, vs best=0.754, vs panel=0.754]
Traceback (most recent call last):                                                                                                                                                          
  File "game_runner.py", line 854, in <module>                                                                                                                                              
    run.track(hit_rate, name='cache_hit_rate',                                                                                                                                              
  File "/home/sakits/anaconda3/envs/demo_2/lib/python3.8/site-packages/aim/sdk/run.py", line 423, in track
    self._track_impl(value, track_time, name, step, epoch, context=context)
  File "/home/sakits/anaconda3/envs/demo_2/lib/python3.8/site-packages/aim/sdk/run.py", line 455, in _track_impl
    self._update_sequence_info(seq_info, ctx, val, name, step)
  File "/home/sakits/anaconda3/envs/demo_2/lib/python3.8/site-packages/aim/sdk/run.py", line 697, in _update_sequence_info
    raise ValueError(f'Cannot log value \'{val}\' on sequence \'{name}\'. Incompatible data types.')
ValueError: Cannot log value '0.16713328471668074' on sequence 'cache_hit_rate'. Incompatible data types.
```
Is it because I have the wrong version of requirements installed or something else?

Thanks!

**Comment by bhansconnect** [comment] 2022-04-08 05:37
I haven't used the cache since changing to aim. I think I know what the issue is. The first iteration the cache isn't used so the value will be 0. That is an integer. After that, the value is a float.

I am running an experiment right now that I don't want to mess with, so I can't test, but can you try changing it to `float(hit_rate)` on that line? You may need also remove the old model from aim to clear `cache_hit_rate` being an int. `aim runs ls` folllowed by `aim runs rm ...`. Could also delete the `.aim` directory and re-initialize it.

**Comment by Sakits** [comment] 2022-04-08 10:48
It seems to be working great after modifying as you said, thanks!

**Comment by bhansconnect** [comment] 2022-04-08 18:16
Pushed a fix commit

**Closed as completed by bhansconnect** 2022-04-08 18:16 UTC
